### ISSUE TITLE
Paths.draw() error

### ISSUE THREAD

**Issue by lycoreus** [tryolabs/norfair#96]
Hi all, 

When I call Paths.draw() I get the following error even though draw_tracked_objects(), which gets the same input arguments, works fine.

```
Traceback (most recent call last):
  File "C:\Users\path/1445870238.py", line 76, in <module>
    Paths.draw(original_frame, tracked_objects)
TypeError: draw() missing 1 required positional argument: 'tracked_objects'
```

**Comment by joaqo** [comment]
Hi @lycoreus ! We just added `Paths` to Norfair (its hasn't been added to a pip release yet) so it is possible it has issues. I just merged a fix to one of those issues, and think it should be working fine now.

Having said that, your particular issue seems to be from a misuse of `Path.draw`'s api, as it seems you're missing an argument when invoking it. [Here](https://github.com/tryolabs/norfair/blob/master/docs/README.md#pathsdraw) is the function's signature in case you wanna try again.

Please let us know if you find any other issues!

**Comment by lycoreus** [comment]
Hi @joaqo ! I updated the drawing.py file but still have the same issue. Here is the relevant part of my code:

here I import the modules:
`from norfair import Detection, Tracker, Video, draw_tracked_objects, draw_points, draw_debug_metrics, print_objects_as_table, Paths`
here is the suntax:
`detections = [Detection(p) for p in detections]
        tracked_objects = tracker.update(detections=detections)
        Paths.draw(original_frame, tracked_objects)
        #draw_tracked_objects(original_frame, tracked_objects)`
        
Note that `draw_tracked_objects(original_frame, tracked_objects)` works fine.

**Comment by joaqo** [comment]
Hi @lycoreus. I think the issue with your code is that you first have to instantiate an instance of `Path`, before you can call its `draw` method. The [api docs](https://github.com/tryolabs/norfair/blob/master/docs/README.md#paths) on Path may be helpful.

**Comment by lycoreus** [comment]
Thank you @joaqo! It worked. The result though is not what I expected. Instead of a path I only get a circle drawn on every tracked object (similar to draw_tracked_objects just without the numbers). Past positions are not drawn. I tried `paths = Paths(attenuation=0)` but I still only get a circle per tracked object per frame. Note that I call `paths.draw()` once every frame.

**Comment by joaqo** [comment]
Hi, I just checked our [YOLOv5 demo](https://github.com/tryolabs/norfair/blob/master/demos/yolov5/yolov5demo.py) and the paths functionality is working correctly. There may be 2 possible sources for your issue:

1. You were not running a local clone of Norfair with the latest commits. This is no longer an issue as we just released a new version of Norfair to PyPI (v0.4.3), which includes all the `Paths` functionalities. So maybe update Norfair and try again if you weren't running it locally.
2. There is an error in your code. To make sure this isn't the case try out the YOLOv5 demo I posted above, which draws the paths correctly.

Good luck!
